### ISSUE TITLE
New UX - 4.1 shortness of breath follow up

### ISSUE THREAD

**Issue by danamlewis** [Co-Epi/app-android#118]
See Figma for latest

![image](https://user-images.githubusercontent.com/7468165/80319863-be598180-87c7-11ea-80ea-65b7269b4e5c.png)

(circles will include graphic visuals)

**Comment by danamlewis** [comment]
@yibter  figma now has icons to pull in

**Comment by i-schuetz** [comment]
@yibter This will be implemented with a recycler view, right?

**Comment by yibter** [comment]
@i-schuetz The gradient line in the background behind the icons had me leaning towards static, but I'll see if I can pull that off in a dynamic way (ex. recycler). Feels like the UX we're exploring here is kinda like a vertical slider, so a themed native control would be awesome here -- but yeah, for now I'm just doing buttons with drawableLeft to mimic the mock.

**Comment by i-schuetz** [comment]
@yibter With these colors we just have to tell the cell the colors of the top and bottom segment (and whether there's a segment). Even if it was a continuous gradient, we could connect the ending and starting values. What do you mean with vertical slider? Do you think there will be a use case where we slide through these values instead of tapping them individually?

**Comment by yibter** [comment]
@i-schuetz Yeah totally, what you're describing is the fun stuff we're going to have to do if we wanna make this component more reusable/data-driven. And yeah, this reminded me of a vertical slider/seekbar -- where there's min/max with increments in between and a bar connecting the single user-selectable value.
