### ISSUE TITLE
Configure linter

### ISSUE THREAD

**Issue by ivnsch** [Co-Epi/app-android#200]
And integrate in CI process. Linter errors should fail the build and not allow to merge PRs.

**Comment by mellowgeek** [comment]
With #199 implemented, we can add a step to run detekt as well.

**Comment by ivnsch** [comment]
Any news on this?

**Comment by laurenipsum365** [comment]
@i-schuetz I've got the configuration file modified so that it won't break the builds now (having to ignore things that we might want to change down the line like MagicNumbers and ComplexMethods etc. Also I am allowing up to 25 code smells (otherwise builds would break right now because of all of the code smells). But all I need to do is add this task to the android yaml file file for the CI build.
