### ISSUE TITLE
Update Exposure Alert View on Selection

### ISSUE THREAD

**Issue by haleybear** [Co-Epi/app-android#240]
**Is your feature request related to a problem? Please describe.**
It feels awkward and counterintuitive to navigate to the Exposure Alert screen and then drag down to force an update.

**Describe the solution you'd like**
It would be nice if the Exposure Alert screen is up to date when I access it, without further actions. Ideally this would be implemented in the early versions of the application.

**Describe alternatives you've considered**
Another alternative would be smaller intervals that it updates at, if it is not going to auto update.

**Additional context**
This is something that I noticed while replicating another issue:
https://github.com/Co-Epi/app-android/issues/196

**Comment by i-schuetz** [comment]
The alerts auto-update each 15 mins. We added the pull to refresh to make testing easier. A shorter update interval doesn't seem meaningful for this app. You contacted a user 5 week ago, that decided to submit a report 2 days after or so, receiving the notification 10 mins earlier doesn't seem to make a substantial difference.

**Comment by ivnsch** [comment]
The alerts auto-update each 15 mins. 

If with 
> It would be nice if the Exposure Alert screen is up to date when I access it

You mean that we should update the alerts each time the user opens the screen, I'm not sure that it's necessary, given the auto-update. The pull to refresh was not really intended for regular users, but to make testing easier.

**Comment by SSNimnicht** [comment]
Currently, there is no indication on the Exposure Alert screen as to when the information was last updated so the user will believe that the information is current because ALL other applications update when a user accesses the screen for specific information.  Why would this screen operate differently?  Believing that users will access the Exposure Alert screen every 15 minutes or less is unrealistic.

**Comment by haleybear** [comment]
In a situation where a user has no exposure alerts on opening the app it will be incredibly jarring to have it auto-update and show a slew of new exposures. That stress could be minimized through allowing the user to access as often as they choose as well as the 15-minute interval for updating when they have the app minimized or their phone put away.

**Comment by ivnsch** [comment]
@SSNimnicht for our use case immediate notifications don't seem very useful. E.g. there was a contact with a symptomatic user 1 week ago, the user decided to submit a report 2 days later. A delay of max. 15 minutes after the report was submitted doesn't seem to make a substantial difference for the user receiving the alert.

The exposure matching is also processor intensive and can drain the battery, so if there's not a valid reason I'd definitely not run it more often than each 15 mins. On iOS IIRC the interval is even longer.

@haleybear 

> it will be incredibly jarring to have it auto-update and show a slew of new exposures

Unless you're opening the alerts screen several times in each 15 mins interval, which I don't see a regular user doing, I don't see how this is different than waiting 15 mins. I also think that the case where a user will receive a "slew of new exposures" for a 15 mins interval is unlikely: even if you had contact with a lot of infected users, it would mean that all of them decided to submit the report in this 15 mins interval.

I'm principally not against showing users e.g. when was the last time that the alerts were fetched, though I personally wouldn't prioritize it, because of reasons mentioned above. The usability scenarios here are different to e.g. a news app.

Edit: Note when the app is in the background, the intervals may be longer, due to OS scheduling.

**Comment by i-schuetz** [comment]
Actually, forgot to mention the most important point: the exposure matching can take several minutes (it definitely will in production with thousands of downloaded reports and stored TCNs). So it doesn't make sense to update when you open the screen. We likely will even have to make the intervals longer.

**Comment by ivnsch** [comment]
Actually, forgot to mention the most important point: the exposure matching can take several minutes (at least in production, when available to a large enough area, with possibly thousands of downloaded reports). So it doesn't make sense to update when you open the screen. We may even have to make the intervals longer.

**Comment by ivnsch** [comment]
I'll interpret the lack of further comments as agreement and close this. Feel free to comment / reopen.
