### ISSUE TITLE
QUESTION:  Correct Flow for No Symptoms?

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#245]
Seen on Pixel 2 0.3(67) commit 22bfa86 with Android OS 10 the attached logs.

I had originally accidentally put in a symptom so I resubmitted I have no symptoms.  The attached logs "appear" to show a work flow issue that is then shortly followed by a functional work flow.  Is the attached indicative of an issue?  If so, do you need more details as to how I did this?

![No_Symptoms_Log_part1](https://user-images.githubusercontent.com/67011880/84947129-b4614a00-b0b7-11ea-93d1-b7eaad9ab295.png)

![No_Symptoms_Log_part2](https://user-images.githubusercontent.com/67011880/84947147-b88d6780-b0b7-11ea-91f8-b97dd87ce5d4.png)

**Comment by i-schuetz** [comment]
IIRC there were no issues with the app, right?

The logs: 

1) "Symptoms ids is empty" -> This is shown when you try to start the flow without having selected anything. It shouldn't happen, since the button should be disabled, thus a warning. We have to investigate.

2) "Couldn't start flow" -> Is caused by the issue above.

3) "TODO handle inputs OTHER / NONE" -> This is a non-issue. The log message is wrong and should be removed.

**Comment by ivnsch** [comment]
Can you describe in more detail the behavior of the app? It's unclear to me whether it worked as expected or not.

The logs:

1. "Symptoms ids is empty" -> This is shown when you try to start the flow without having selected anything. It shouldn't happen, since the button should be disabled, thus a warning. We have to investigate.

2. "Couldn't start flow" -> Is caused by the issue above.

3. "TODO handle inputs OTHER / NONE" -> This is a non-issue. The log message is wrong and should be removed.

**Comment by SSNimnicht** [comment]
Apologies for the unclear details on the app behavior.  As a normal user (without debug available), the app appears to work correctly in that it thanks me for logging my symptoms when I said I was symptom free.  It allows for navigation to the Symptom Report, Home and Exposure Alert Screens.

**Comment by ivnsch** [comment]
I'm not being able to reproduce any warning or error log messages. I tried:

Flow 1:
1. Select symptom report
2. Select loss of smell or taste, submit, select time
3. Select update symptom report
4. Select no symptoms, submit

Flow 2:
Same as Flow 1 but with "cough" in step 2

Flow 3:
Same as Flow 1 but pressing back button in thanks screen (step 3).

Flow 4:
Same as Flow 1 but re-submitting via back to home, select symptom report.

Maybe it was fixed in the meantime? I'll close this for now, feel free to reopen if it can be reproduced.

**Comment by ivnsch** [comment]
Note:

> 3. "TODO handle inputs OTHER / NONE" -> This is a non-issue. The log message is wrong and should be removed.

This was resolved.

**Comment by SSNimnicht** [comment]
Cannot duplicate issue in Android commit 679cfca [0.3 (95)]
