### ISSUE TITLE
Display Commit Hash for Currently Installed SW in Debug Log-Android

### ISSUE THREAD

**Issue by SSNimnicht** [Co-Epi/app-android#292]
**Is your feature request related to a problem? Please describe.**
When cloning the current Android repository into Android Studio and then pushing from Android Studio to my Android device, the real version is not displayed at the bottom [Something like 0.3 (3) displays which is NOT accurate.].  This is unlike when I use the App Center CoEpi-Android Install button in the automated emails I was fortunate to receive.  With this process, I do get the version number.

**Describe the solution you'd like**
With either method of installing the Android application, it would be nice to have the commit hash in the debug log just for double checking purposes while testing and logging questions, comments and issues.

**Comment by i-schuetz** [comment]
Displaying the commit hash in the local builds is not possible, because the app doesn't have knowledge of git. Even if it accessed it via api, it wouldn't know which commit commit you checked out. I also don't see the need for this. You should be able to check easily on the computer which commit you've checked out.

**Comment by i-schuetz** [comment]
Displaying the commit hash in the local builds is not possible, because the app doesn't have knowledge of git. Even if it accessed it via api, it wouldn't know which commit you checked out. I also don't see the need for this. You should be able to check easily on the computer which commit you've checked out.
