### ISSUE TITLE
Exposure Alerts 

### ISSUE THREAD

**Issue by haskinselena** [Co-Epi/app-android#312]
**Individual exposure alerts**
1. Timeline of repeated interactions previously logged
2. Distance from you on exposure alert
3. Menu button in header to delete

<img width="845" alt="Screen Shot 2020-07-21 at 6 08 03 PM" src="https://user-images.githubusercontent.com/67452742/88112149-42c86000-cb7d-11ea-8148-0f41b54f1e72.png">

**Exposure alert screen** 

1. Red dots to indicate new alert - will disappear once clicked
2. Preview of first symptoms will show (similar to a text)
3. Blue boxed indicator to represent if an interaction is repeated (the user has already interacted with the same  person previously)
4. Definition of exposure alerts under title

<img width="424" alt="Screen Shot 2020-07-21 at 7 48 37 PM" src="https://user-images.githubusercontent.com/67452742/88118290-3945f480-cb8b-11ea-9826-908efff4cfd2.png">

**Comment by ivnsch** [comment]
@Co-Epi/ux while we agreed to keep the main design cross-platform, there are some details, like the "more" button in the top bar, or the action sheet, that should be within the platform's guidelines (it looks very awkward otherwise + it's also difficult to deviate implementation-wise).

More button and menu on Android, see https://material.io/components/app-bars-top#anatomy, https://material.io/components/menus#dropdown-menu

The [action sheet](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/) is pretty much iOS-only.

**Comment by i-schuetz** [comment]
@Co-Epi/ux There's an option "Report a problem": can you specify what should happen here? If we should open an email client, can you provide the pre-fill data?

**Comment by haskinselena** [comment]
For Android you can do this:
<img width="929" alt="Screen Shot 2020-07-23 at 11 43 22 PM" src="https://user-images.githubusercontent.com/67452742/88358790-5e2e9900-cd3e-11ea-9ab0-98fb96b4e2ae.png">

**Comment by ivnsch** [comment]
@haskinselena on Android it's slightly more convenient to use SVG for the linked alerts shape (the grey vertical line with circles), but I'm having problems exporting it in Figma (the circle+line exports only circle). Can you please provide 3 SVGs: 1. top cell: circle+line, 2. center cells: just a line, 3. bottom cell: line+circle?

**Comment by haskinselena** [comment]
Try this @i-schuetz : 
[exposure_assets.zip](https://github.com/Co-Epi/app-android/files/5001564/exposure_assets.zip)

Let me know if this works or you need more

**Comment by ivnsch** [comment]
Actually I changed my mind, since the cells have variable height the SVG isn't ideal. Thanks anyway.
