### ISSUE TITLE
Symptom timing

### ISSUE THREAD

**Issue by scottleibrand** [Co-Epi/app-android#72]
Once users select symptoms, prompt them to pick a date when each of the selected symptoms started.

**Comment by i-schuetz** [comment]
The (CoEpi specific) format of the memo is still TBD, right? Or has there been progress already?

**Comment by scottleibrand** [comment]
@hdevalence or @bhushanRamnani do you know of any work that's already been done to specify this? If not, then I think it's still TBD.

**Comment by bhushanRamnani** [comment]
Nope. There isn't any specific field in the protocol or the back-end API being build for it. Although, I think this information can be squeezed into the 256 byte memo with starting 4 bytes being the symptom time in epoch seconds.

**Comment by i-schuetz** [comment]
We probably should use a custom timestamp, to occupy as little space as possible. We probably don't need seconds (or minutes/hours?) resolution and can use a recent reference date.

**Comment by i-schuetz** [comment]
We probably should use a custom timestamp, to occupy as little space as possible. We probably don't need seconds (or minutes/hours?) resolution and can use a recent reference date. If we consider that (at least for the current purpose) we're not interested in dates older than ~3 weeks, we may be able to make it fit in 1 byte or less. We can also set a reference timestamp (lowest needed resolution) and define the per-symptom time in reference to it.

**Comment by hdevalence** [comment]
To my knowledge there hasn't been any work defining the CoEpi payload yet, just an allocation of a memo type.

I wonder whether it is really necessary to specify symptom timing in the report.  If we assume that each report covers only a short time interval (less than a day, say), then it's unlikely that symptom development is below the timing resolution already provided by the report.  In other words, instead of including a symptom timing, the user can specify for each symptom when they observed symptom S_i, and the application can include in each report just a bitflag of all the symptoms that the user experienced at the time of that report.  Is there a reason that this wouldn't work?

**Comment by scottleibrand** [comment]
We discussed this a bit on the CoEpi call this evening.

If you just tell people whether or not you were symptomatic at the time they came in contact with you, you miss about half of the transmission events: 
![image](https://user-images.githubusercontent.com/6982790/80439981-98fa6f80-88bc-11ea-9790-7ef6309f312f.png)

Instead, I think what we want to do is report the date of the first symptoms, the bitflag of all symptoms the user has experienced since, and the general severity level (to only a few bits of precision) on any non-binary symptoms (like cough, fever, etc.). That should be sufficient to give people all the information they need to make an informed decision about whether to self-quarantine while reducing the likelihood that people reporting symptoms can be uniquely fingerprinted across everyone in a geoshard for linkage attacks.

**Comment by Joshua-McCord** [comment]
Is this ticket related to #153 ? If so, we could go ahead and link the issues, I currently have #153 close to being done.

**Comment by danamlewis** [comment]
Completed in v0.3, closing.
